name: Scrape Latest Rumble Videos

on:
  schedule:
    # Runs at 13:00, 17:00, 21:00, and 01:00 UTC (approx 8am, 12pm, 4pm, 8pm CT - adjust as needed)
    - cron: '0 13,17,21,1 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Use latest version
        with:
          node-version: '18' # Or your preferred Node version >= 18

      # Install dependencies needed for Puppeteer in headless Linux
      - name: Install OS Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq libatk1.0-0 libatk-bridge2.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils fonts-liberation libu2f-udev libvulkan1

      # Install project dependencies (including Puppeteer)
      - name: Install Node Dependencies
        run: npm install

      # Install Wrangler globally for command-line execution
      - name: Install Wrangler
        run: sudo npm install -g wrangler

      - name: Run Scraper and Update Script
        env:
          # Pass Cloudflare credentials from GitHub Secrets
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          # Note: DB name is hardcoded in the script currently, or could be passed too
        run: node update-videos.js

      # Optional: Add error handling/notifications here if needed